### ISSUE TITLE
Adjust the home page to more closely represent Kate's design

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#101]
The home page isn't quite matching Kate's design. We need the following changes:
- Change first yellow box question to "Do I take the census?"
- Remove the "Everyone Matters" header and following paragraphs.
- Move the video to below the row of yellow boxes
- Put the new copy into the yellow boxes (I'll add it in the comments as I get it for each box).
- Add a "top 5 reasons to take the census" section.)

**Comment by aelar13** [comment]
New copy for the Sample Survey yellow box:
**Should I be completing the questionnaire?**
_What will I be asked?_
Learn more about the census questions, and who should be answering the questionnaire.

**Comment by aelar13** [comment]
QR code yellow box:
Use the In a hurry, take it to go! and sub header, but remove all the text and links in the white box, and just put in the QR Code instead, larger.

**Comment by aelar13** [comment]
FAQ Yellow box:
Is it safe?
Why should I be counted?
Get the answers to all your questions about why to take the census and how the information will be used.

**Comment by ianHunterClipd** [comment]
@turnerhayes I added a Top Reasons component to the home screen (#103) as I was working on the responsiveness - I didn't read this task closely enough and didn't see it on here.
