### ISSUE TITLE
Put in copy edits for Sample Survey page

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#102]
Change the text below the header to the following:
You should complete the questionnaire as "Person 1", if you are responsible for the home.  If you live in someone else's home, you will need to provide information to the person completing the questionnaire.  See what information will need to complete the questionnaire.

Change the button text to:
I will answer the census.
Someone else will answer for me.

**Comment by aelar13** [comment]
Adjust the spacing as follows:
- Increase the padding above the main header
- Decrease the line spacing about 25% between header and following paragraph text
- Reduce the size of the big buttons, both the button size and the text. Align the button size with the row of buttons below
- Reduce the padding between the rows of buttons and the main panel
- Increase the spacing between the bar under the question, before the first yellow response.

**Comment by ianHunterClipd** [comment]
on it
