### ISSUE TITLE
performance: Serve static assets with an efficient cache policy

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/census2020#118]
According to this [audit report from Chrome Dev Tools](https://github.com/codeforsanjose/census2020/files/4054578/Census2020-Audit-Report-0122020.pdf), this can be enhanced to improve performance: 

A long cache lifetime can speed up repeat visits to your page. Learn more. https://web.dev/uses-long-cache-ttl?utm_source=lighthouse&utm_medium=devtools
URL | Cache TTL | Size
-- | -- | --
…pl4RO5EisCU/maxresdefault.jpg(i.ytimg.com) | 2 h | 91 KB
…s68-c-k-no-mo-rj-c0xffffff/photo.jpg(yt3.ggpht.com) | 1 d | 4 KB
…en_US/base.js(www.youtube.com) | 8 d | 398 KB
…www-embed…/www-embed-player.js(www.youtube.com) | 8 d | 39 KB
…www-widgetapi-vfl497i6p/www-widgetapi.js(s.ytimg.com) | 8 d | 16 KB
…en_US/embed.js(www.youtube.com) | 8 d | 3 KB

**Comment by turnerhayes** [comment]
afaict, there's nothing we can do about these--these are all third-party (Youtube) resources.
