### ISSUE TITLE
accessibility: Lists do not contain only <li> elements and script supporting elements (<script> and <template>).

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/census2020#126]
According to this [audit report from Chrome Dev Tools](https://github.com/codeforsanjose/census2020/files/4054578/Census2020-Audit-Report-0122020.pdf), this can be enhanced to improve accessibility:

Screen readers have a specific way of announcing lists. Ensuring proper list structure aids screen reader output. Learn more. https://web.dev/list/?utm_source=lighthouse&utm_medium=devtools

Failing Elements
--
```
ul<ul class="control-dots">
Is it safe? Why should I be counted? Get the answers to all your questions abo…<ul class="c_home__factoids">
Top 5 Reasons to take the census Determines the number of seats in the House o…<ol class="c_home__top-reasons c_home__top-reasons__small">
```

**Comment by turnerhayes** [comment]
The remaining issue in this category is from the react-responsive-carousel library, for which I have opened an issue: https://github.com/leandrowd/react-responsive-carousel/issues/399
