### ISSUE TITLE
bug: Sample Survey is broken

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/census2020#128]
- [ ] You can't enter the number of people in question 1
- [ ] You can't select from the checklists, and there is boilerplate language that needs to be removed.  - [ ] There's no information under the placeholder questions: How to answer this question, How is this info used, and Why answer this question.
- [ ] If you select Someone else will answer the census for me, the questions don't even exist.

If this is a work in progress section, please consider disabling the text and write a disclaimer up top so it's clear the survey part is WIP. 

Or, if the section isn't supposed to be a form, then don't make it function like a form, e.g. providing an input textarea.

**Comment by ianHunterClipd** [comment]
Remaining aspect of this bug consolidated to #139
