### ISSUE TITLE
Make the app mobile responsive

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/census2020#131]
I was looking on your app on my phone and noticed some things are off. 

The text up top is overlapping (the buttons for in Spanish and Vietnamese)

The Take the Census button overlaps the menu bar. Is that intentional?

![Screenshot_20200122-202215](https://user-images.githubusercontent.com/20962963/72958077-d1892b00-3d5a-11ea-9699-7ce2be554b27.jpg)

The `+` sign is either outside or inside the box. When it's inside, it almost looks like it's part of the sentence, which isn't clear that it's something you should click on to expand for info. 

![Screenshot_20200122-202200](https://user-images.githubusercontent.com/20962963/72958078-d1892b00-3d5a-11ea-8db9-a79b38b66440.jpg)

When  you do click on `+` button, sometimes the text overflows outside of the box and you have to scroll to the right to see all the text.
![Screenshot_20200122-202151](https://user-images.githubusercontent.com/20962963/72958079-d1892b00-3d5a-11ea-9f2d-14d2bf86a442.jpg)

**Comment by ianHunterClipd** [comment]
Responsive header and footer implemented. Additional responsiveness to be added to FAQ page in upcoming PR.

**Comment by ychoy** [comment]
Thanks for addressing this, @ianHunterClipd! In the future, can you please tag the issue in the description of the PR? For example "Fixes #131" will close the issue, or "Addresses #131" will link it in this history so if anyone is making a similar issue, or needs to reference the history, they can see how it got fixed :)
