### ISSUE TITLE
Reformat Contact Page to Match Hi-Fi (Body Only)

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#34]
As a San Jose Census2020 kiosk user, I need the contact form to match the standard design for the site.

Note: This issue is focused on just the body of the contact form. The header and footer are separate designs that should be implemented on all pages.

Acceptance Criteria:
- Contact form page (a.k.a. Get Involved) should match the fields and format in the following design: https://projects.invisionapp.com/share/8QTLAQGGZT5#/screens/380419015
- Form page should be created using components from the US web design system https://designsystem.digital.gov/
- Header and footer should be pulled in/match the design from those separate issues.

-

**Comment by turnerhayes** [comment]
Do we have the image for the contact form? Not that it's a blocker, just wondering if that's ready to go.

**Comment by aelar13** [comment]
I think this has been accomplished, other than some image resources and any tweaks to the design we come up with later, so I'm closing it. I'll open a new issue for the correct image.
