### ISSUE TITLE
Add email validation to the Contacts form

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#35]
As a San Jose Census 2020 program manager, I need the email field in the contact form to have basic validation so that the emails have a high likelihood of being valid.

Acceptance Criteria

- Email address field has basic validation to ensure the inputted text appears to be an email address.
- Perform validation when the user exits the field.
- If the email address field does not pass validation, do not allow the form to submit.
- If the email address field does not pass validation, provide an inline warning message to the user. 
- Clear this message once the address is valid.

**Comment by christian-r-n** [comment]
I'll take a look at this

**Comment by aelar13** [comment]
The error message for this should read: Please enter a valid email address.
