### ISSUE TITLE
Create Header for the Site

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#36]
As a San Jose Census 2020 kiosk visitor, I need a consistent header design so that I always know where I am and what I can do.

Acceptance Criteria

- Replicate the Hi-Fi Header design. See here for an example: 
https://projects.invisionapp.com/share/8QTLAQGGZT5#/screens/380419015
- Header should be coded using components from the US web design system https://designsystem.digital.gov/
- Header should be used as is on all pages of the site.

**Comment by turnerhayes** [comment]
Do we have the assets for the logos, and the various icons (US flag, globe icon)?

How about for the "Here's how you know" link; any specs for what that should look like expanded (assuming it's a dropdown sort of thing)?

**Comment by turnerhayes** [comment]
Also, more generally: do we have a font for the site?

And it would be useful (to me) to have specs for things like font sizes of headers, dimensions of buttons (e.g. the Take the Census button), and color codes.
