### ISSUE TITLE
Add Email Auto Response to Contact Form

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#38]
As a San Jose Census 2020 kiosk user, I want an email response to any contact form so that I will know my request was received and that someone will answer.

Acceptance Criteria
- When a form is submitted, an email is automatically sent to the email entered by the requester.
- The email begins with the name entered, thanks the user, and lists their response to the Interest question and any comments. It ends with a statement that someone will respond within two business days.
- The standard strings will be translated if the requester was on the Spanish or Vietnamese version of the page.

**Comment by turnerhayes** [comment]
Do we have copy for the auto response email?

**Comment by aelar13** [comment]
If we don't get a content person today, We can use something like: 

Hi [User name],

Thank you for your interest in the 2020 Census effort in San Jose.

The following message was sent by you to the City of San Jose Census Office:

// Format the following indented, like a quote//
 
I have an interest in:
[Interest responses here, one per line]

//If they entered a comment//
Additional comments:
[Additional comments text here]

[Text of the comments]

//End indent//

Thank you again for your interest. Someone will respond back to you within two business days.

--City of San Jose 2020 Census Office

**Comment by aelar13** [comment]
We had some minor updates to the text above (no changes to the fields).
