### ISSUE TITLE
Email Form Response to the City of San Jose Census Email

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#39]
As the City of San Jose Census 2020 project leader, I need to receive a well formatted email whenever someone submits a form, so that I can respond.

Acceptance Criteria
- When a form is submitted, send an email to 2020census@sanjoseca.gov 
- Include an introduction "There was a form submission from the San Jose Census 2020 website" and list the responses, along with a date and timestamp
- If the form was submitted from the Spanish or Vietnamese site, include "Language: Spanish" for example, but list the form fields by their English names (but leave any comments in their language).

**Comment by turnerhayes** [comment]
Is a date/time useful? Can the date/time information on the email itself be used to get that information? It'll be maybe a few seconds off from the actual submission time (unless something goes haywire with the mail server) but should be close enough.

**Comment by turnerhayes** [comment]
The to address is configurable, so we just need to make sure to configure it properly wherever we end up deploying the site; the address shouldn't require any code changes.

**Comment by aelar13** [comment]
Yes, absolutely date time should be useful, and doesn't need to be exact. Date and time just to the minute will be more than enough, non-techies get disoriented with seconds and stuff.

The date time in the body of the email is needed because if things get forwarded around, the original date time on the email can get lost.

**Comment by turnerhayes** [comment]
Fair enough; I think forwards typically include that information by default, but it makes sense not to assume that they will.
