### ISSUE TITLE
Code the Home Page Design

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#55]
As a user of the website, I need a home page with information on the Census, so that I can be convinced to do my civic duty.

Acceptance Criteria:
- Home page/landing page is coded according to the Zepplin design
- All images and text are available

**Comment by ianHunterClipd** [comment]
On it! 

But - I need access to the image resources.

**Comment by turnerhayes** [comment]
@ianHunterClipd has finished this in #66
