### ISSUE TITLE
Replace Image on the Get Involved Page

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#58]
As a visitor to the Get Involved page, I want to see something related to Census2020, so that I know I am on the right page.

Acceptance Criteria
- Replace current image with image provided by Vilcia
- Image relates to Census 2020

**Comment by aelar13** [comment]
This one isn't ready to be worked on. I'm going to start by getting a photo from Vilcia.

**Comment by turnerhayes** [comment]
@aelar13 what's the status of this photo?

**Comment by aelar13** [comment]
![censusliterature](https://user-images.githubusercontent.com/49049018/76032167-24273c80-5eee-11ea-97e1-651b6e53d0c3.jpg)
Here's the file to replace the current one on the Get Involved page.
