### ISSUE TITLE
Format FAQ Page to Match the Zepplin Design

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#60]
As a San Jose Census2020 kiosk user, I need the FAQ to be readable and match the standard design for the site.

Note: This issue is focused on just the body of the FAQ. The header and footer are separate designs that should be implemented on all pages.

Acceptance Criteria:
- FAQ should match the fields and format in the Zeppelin design. (If there are any questions, message the Slack channel!)
- FAQ page should use/be inspired by components from the US web design system where useful/possible: https://designsystem.digital.gov/
- Header and footer should be pulled in/match the design from those separate issues.

**Comment by aelar13** [comment]
Josie is working on this.

**Comment by aelar13** [comment]
The actual content for the FAQ will be a different ticket. Filler text can be used in the meantime.

**Comment by turnerhayes** [comment]
I believe this is now obsolete-- @aelar13 please reopen if it isn't
