### ISSUE TITLE
Edit Home Page Text

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#71]
The United States 2020 Census 
When you respond, we all benefit. 
 
Answer Confidentially 
Online, by Phone, or by Mail 
 

The 2020 Census is here. Your participation helps ensure our community will have access to housing, healthcare, schools, community programs, better transportation, and government representation. 

Every 10 years, the U.S. Census Bureau sets out to count every person living in the United States — regardless of age, citizenship status, and gender. Getting the 2020 Census right is important for all our communities — particularly those most likely to be undercounted. A 2020 Census undercount could put billions of federal dollars and congressional representation for California at risk!

Complete the census survey **online, by phone or mail**. The process is easy, quick and confidential! All you need is the ID code mailed to you by the U.S. Census Bureau, or your mailing address. Remember, to _include everyone living and sleeping in your house_. That means babies, children, teens, roommates, etc. Click the "Take the Census Now" button to get started!

**Comment by turnerhayes** [comment]
Is this still valid in the new mocks? The [home page here](https://www.figma.com/file/5fgkTZjeBKML4GHHSfw5Hn/Mocks?node-id=9%3A20) doesn't look like it has paragraphs, just a sentence and factoid boxes.

**Comment by aelar13** [comment]
This should still be valid, but the new mockups needed some adjustment to find a middle ground. I would put this text into the current homepage while we work out the final tweaks to the front page.
