### ISSUE TITLE
Make header and census button sticky

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#72]
We need the header and census button to remain at the top even if we scroll.

**Comment by aelar13** [comment]
The header under the logo should also have a circular radius that scrolls with the page. See this mockup:
https://www.figma.com/proto/5fgkTZjeBKML4GHHSfw5Hn/Mocks?node-id=9%3A20&scaling=min-zoom

**Comment by turnerhayes** [comment]
Note: circular radius (and other new header styles) implemented in #75.
