### ISSUE TITLE
Implement Sample Survey Design

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#73]
Create a Sample Survey page based on the design at 👍 https://www.figma.com/proto/5fgkTZjeBKML4GHHSfw5Hn/Mocks?node-id=5%3A1&scaling=min-zoom
(the second page)
The top has a navigation series of links through the questions. The main part of the page has a section showing the text of the current question, and information in three areas, set off by colored headers.

We might need to play with how to make the text for each survey question accessible to someone using a screen reader, since the implementation is hiding the text for each page. If the accessibility challenge is too hard, we could start by doing a new page for each survey question.

**Comment by aelar13** [comment]
Placeholder text can be used for the other information, but here is formatted text for all the question information (above the horizontal rule):

**Q1. How many people were living or staying in this house, apartment, or mobile home on April 1, 2020?**

**Number of people =** [Textbox]

**Q2. Were there any additional people staying here on April 1, 2020 that you did not include in Question 1?**
_Mark all that apply._
[] Children, related or unrelated, such as newborn babies, grandchildren, or foster children
[] Relatives, such as adult children, cousins, or in-laws
[] Nonrelatives, such as roommates or live-in babysitters
[] People staying here temporarily
[] No additional people 

**Q3. Is this house, apartment, or mobile home** _— Mark ONE box_
[] Owned by you or someone in this household with a mortgage or loan? Include home equity loans.
[] Owned by you or someone in this household free and clear (without a mortgage or loan)?
[] Rented?
[] Occupied without payment of rent?

**Q4. What is your telephone number?**
_We will only contact you if needed for official Census Bureau business._
Telephone Number
[Textbox]–[Textbox]–[Textbox]

**Q5. Please provide information for each person living here. If there is someone living here who pays the rent or owns this residence, start by listing him or her as Person 1. If the owner or the person who pays the rent does not live here, start by listing any adult living here as Person 1.**

**What is Person 1’s name?** _Print name below._
First Name [Textbox] MI [Textbox]
Last Name(s) [Textbox]

**Q6. What is Person 1’s sex?** _Mark ONE box._
[] Male [] Female 

**Q7. What is Person 1’s age and what is Person 1’s date of birth?** _For babies less than 1 year old, do not write the age in months. Write 0 as the age._
Age on April 1, 2020
[Textbox] years
Month [Textbox] Day [Textbox] Year of birth [Textbox]

Q8. Is Person 1 of Hispanic, Latino, or Spanish origin?
[] No, not of Hispanic, Latino, or Spanish origin
[] Yes, Mexican, Mexican Am., Chicano
[] Yes, Puerto Rican
[] Yes, Cuban
[] Yes, another Hispanic, Latino, or Spanish origin – Print, for example, Salvadoran, Dominicican, Colombian, Guatemalan, Spaniard, Ecuadorian, etc. [Textbox]

**Q. 9 What is Person 1’s race?**
_Mark one or more boxes AND print origins._
[] White _– Print, for example, German, Irish, English, Italian, Lebanese, Egyptian, etc._ [Textbox]
[] Black or African Am. _– Print, for example, African American, Jamaican, Haitian, Nigerian, Ethiopian, Somali, etc._ [Textbox]
[] American Indian or Alaska Native _– Print name of enrolled or principal tribe(s), for example, Navajo Nation, Blackfeet Tribe, Mayan, Aztec, Native Village of Barrow Inupiat Traditional Government, Nome Eskimo Community, etc._ [Textbox]
[] Chinese
[] Filipino
[] Asian Indian
[] Vietnamese
[] Korean
[] Japanese
[] Native Hawaiian
[] Samoan
[] Chamorro
[] Other Asian _– Print, for example, Pakistani, Cambodian, Hmong, etc._ [Textbox]
[] Other Pacific Islander _– Print, for example, Tongan, Fijian, Marshallese, etc._ [Textbox]
[] Some other race _– Print race or origin._ [Textbox]

**Comment by aelar13** [comment]
Notes about the textboxes and check boxes: We need some visual indicator that responses are meant to be checkboxes or textboxes, but they need to not be editable or clickable, to avoid confusing visitors to the site about whether they are actually filling out the census now or not.

**Comment by aelar13** [comment]
Also: The above 9 questions need to be filled out for Person 1, but there is an additional set for subsequent people that is slightly different. I think we might need to add them as A1 - A7 to be complete, not sure how exactly to handle it.

Here are those questions, in case we need it:

**A1. What is Person 2’s name?** _Print name below._
First Name [Textbox] MI [Textbox]
Last Name(s) [Textbox]

**A2. Does this person usually live or stay somewhere else?**
_Mark all that apply._
[] No
[] Yes, for college
[] Yes, for a military assignment
[] Yes, for a job or business
[] Yes, in a nursing home
[] Yes, with a parent or other relative
[] Yes, at a seasonal or second residence
[] Yes, in a jail or prison
[] Yes, for another reason

**A3. How is this person related to Person 1?** _Mark ONE box._
[] Opposite-sex husband/wife/spouse
[] Opposite-sex unmarried partner
[] Same-sex husband/wife/spouse
[] Same-sex unmarried partner
[] Biological son or daughter
[] Adopted son or daughter
[] Stepson or stepdaughter
[] Brother or sister
[] Father or mother
[] Grandchild
[] Parent-in-law
[] Son-in-law or daughter-in-law
[] Other relative
[] Roommate or housemate
[] Foster child
[] Other nonrelative

**A4. What is Person 2’s sex?** _Mark ONE box._
[] Male [] Female 

**A5. What is Person 2’s age and what is Person 1’s date of birth?** _For babies less than 1 year old, do not write the age in months. Write 0 as the age._

Age on April 1, 2020
[Textbox] years
Month [Textbox] Day [Textbox] Year of birth [Textbox]

**A6. Is Person 2 of Hispanic, Latino, or Spanish origin?**
[] No, not of Hispanic, Latino, or Spanish origin
[] Yes, Mexican, Mexican Am., Chicano
[] Yes, Puerto Rican
[] Yes, Cuban
[] Yes, another Hispanic, Latino, or Spanish origin _– Print, for example, Salvadoran, Dominicican, Colombian, Guatemalan, Spaniard, Ecuadorian, etc._ [Textbox]

**A7. 9 What is Person 2’s race?**
_Mark one or more boxes AND print origins._
[] White _– Print, for example, German, Irish, English, Italian, Lebanese, Egyptian, etc._ [Textbox]
[] Black or African Am. _– Print, for example, African American, Jamaican, Haitian, Nigerian, Ethiopian, Somali, etc._ [Textbox]
[] American Indian or Alaska Native _– Print name of enrolled or principal tribe(s), for example, Navajo Nation, Blackfeet Tribe, Mayan, Aztec, Native Village of Barrow Inupiat Traditional Government, Nome Eskimo Community, etc._ [Textbox]
[] Chinese
[] Filipino
[] Asian Indian
[] Vietnamese
[] Korean
[] Japanese
[] Native Hawaiian
[] Samoan
[] Chamorro
[] Other Asian _– Print, for example, Pakistani, Cambodian, Hmong, etc._ [Textbox]
[] Other Pacific Islander _– Print, for example, Tongan, Fijian, Marshallese, etc._ [Textbox]
[] Some other race _– Print race or origin._ [Textbox]

**Comment by ianHunterClipd** [comment]
Started in pr #79 . Still need to add FormattedMessages and real census questions.

**Comment by turnerhayes** [comment]
@ianHunterClipd can this be closed?

**Comment by ianHunterClipd** [comment]
@turnerhayes yes I think so
