### ISSUE TITLE
Implement Responsive Designs

### ISSUE THREAD

**Issue by turnerhayes** [codeforsanjose/census2020#78]
https://www.figma.com/file/5fgkTZjeBKML4GHHSfw5Hn/Mocks?node-id=15%3A1674

**Comment by aelar13** [comment]
Ian and I talked through these with Kate, and there are a couple specific action items:

- Set a max width for all large text blocks of 1200px for readability on large screens.
- On mobile, collapse the navigation into a hamburger menu
- Under 800px, collapse the language picker into a dropdown, to save space in the header

**Comment by ianHunterClipd** [comment]
Starting on this now!
