### ISSUE TITLE
Add Overlay and Text to Home Page Header

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#82]
To match Kate's design, lets' reduce the size of the banner images, and add an overlay layer. It would also be good to add in some placeholder text.

Here is some sample text, this could rotate with the header maybe?:
Example 1:
The United States 2020 Census 
When you respond, we all benefit. 

Example 2:
The United States 2020 Census 
Answer online, by phone, or by mail 

Example 3:
The United States 2020 Census 
Your participation affects our congressional representation!

Example 4:
The United States 2020 Census 
Easy, quick and confidential!

Example 5:
The United States 2020 Census 
Be counted San Jose!

**Comment by ghost** [comment]
I can take this one
