### ISSUE TITLE
Add Label Buttons/Switcher to Sample Survey

### ISSUE THREAD

**Issue by aelar13** [codeforsanjose/census2020#94]
Per Kate's design, add the second set of survey buttons, reachable via two buttons Head of Household is default. Non-YOU is the other button.
The text for the seven secondary questions is in issue 73, 4th  comment.

**Comment by SeanKier** [comment]
I take this

**Comment by ghost** [comment]
I can take this

**Comment by SeanKier** [comment]
So looks like Ian actually already had this done. So he's gonna be finishing this up.

**Comment by ghost** [comment]
So looks like Ian actually already had this done. So he's gonna be finishing this up and #102
